export const AUTH_ERROR = 'AUTH_ERROR';
export const USER_LOADED = 'USER_LOADED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const FORGET_PASSWORD = 'FORGET_PASSWORD';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SIDEBAR_COLS = 'SIDEBAR_COLS';

export const USER_LIST = 'USER_LIST';
export const USERS_CLEAR = 'USERS_CLEAR';
export const USER_CLEAR = 'USER_CLEAR';
export const USER_PERPAGE = 'USER_PERPAGE';
export const USER_FETCHPAGE = 'USER_FETCHPAGE';
export const USER_SEARCHTERM = 'USER_SEARCHTERM';
export const USER_SORTORDER = 'USER_SORTORDER';
export const USER_ERROR = 'USER_ERROR';
export const USER_SAVE = 'USER_SAVE';
export const CLEAR_SUCCESS = 'CLEAR_SUCCESS';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const USER_INFO = 'USER_INFO';
export const USER_UPDATE = 'USER_UPDATE';
export const USER_PASSWORD = 'USER_PASSWORD';
export const USER_LOADING = 'USER_LOADING';
export const USER_STATUS = 'USER_STATUS';

export const INVOICE_LIST = 'INVOICE_LIST';
export const INVOICES_CLEAR = 'INVOICES_CLEAR';
export const INVOICE_NUMBER = 'INVOICE_NUMBER';
export const INVOICE_ERROR = 'INVOICE_ERROR';
export const INVOICE_SEARCHTERM = 'INVOICE_SEARCHTERM';
export const INVOICE_FETCHPAGE = 'INVOICE_FETCHPAGE';
export const INVOICE_PERPAGE = 'INVOICE_PERPAGE';
export const INVOICE_SORTORDER = 'INVOICE_SORTORDER';
export const INVOICE_INFO = 'INVOICE_INFO';
export const INVOICE_CLEAR = 'INVOICE_CLEAR';
export const INVOICE_SAVE = 'INVOICE_SAVE';
export const INVOICE_UPDATE = 'INVOICE_UPDATE';
export const INVOICE_LOADING = 'INVOICE_LOADING';
export const INVOICE_SENDLINK = 'INVOICE_SENDLINK';
export const INVOICE_SENDRECEIPT = 'INVOICE_SENDRECEIPT';
export const INVOICE_LINKLOADING = 'INVOICE_LINKLOADING';

export const SPINNER_LOADING = 'SPINNER_LOADING';

export const SERVER_URL = 'http://localhost:5000' ;//'http://localhost:5000'; //'http://18.217.104.6' //Mike Test AWS 'http://3.81.53.5/';